id = "vue"
name = "Vue"
description = "Vue support."
version = "0.2.8"
schema_version = 1
authors = ["Zed Industries <support@zed.dev>"]
repository = "https://github.com/zed-extensions/vue"

[language_servers.vue-language-server]
name = "Vue Language Server"
language = "Vue.js"
language_ids = { "Vue.js" = "vue" }
# REFACTOR is explicitly disabled, as vue-lsp does not adhere to LSP protocol for code actions with these - it
# sends back a CodeAction with neither `command` nor `edits` fields set, which is against the spec.
code_action_kinds = ["", "quickfix", "refactor.rewrite"]

[grammars.vue]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-vue"
commit = "22bdfa6c9fc0f5ffa44c6e938ec46869ac8a99ff"
